feedback/urls.py
from django.urls import path
from . import views

app_name="feedback"

urlpatterns = [
    path('feedback/',views.feedback,name="feedback"),

   
    path('admin_all_department',views.admin_all_department,name="admin_all_department"),
    path('department_delete/<int:id>',views.department_delete,name="department_delete"),
    path('department_update/<int:id>',views.department_update,name="department_update"),
    path('admin_all_feedback',views.admin_all_feedback,name="admin_all_feedback"),
    path('admin_feedback',views.admin_feedback,name="admin_feedback"),
    path('admin_feedback_detail/<int:id>',views.admin_feedback_detail,name="admin_feedback_detail"),
    path('admin_feedback_islemde',views.admin_feedback_islemde,name="admin_feedback_islemde"),
    path('admin_feedback_cozuldu',views.admin_feedback_cozuldu,name="admin_feedback_cozuldu"),
    path('aktif_pasif_update/<int:id>',views.aktif_pasif_update,name="aktif_pasif_update"),
    path('feedback_type',views.feedback_type,name="feedback_type"),
    path('feedback_type_update/<int:id>',views.feedback_type_update,name="feedback_type_update"),
    path('feedback_type_delete/<int:id>',views.feedback_type_delete,name="feedback_type_delete"),
    path('admin_personel',views.admin_personel,name="admin_personel"),
    path('admin_personel_update/<int:id>',views.admin_personel_update,name="admin_personel_update"),
    path('admin_personel_delete/<int:id>',views.admin_personel_delete,name="admin_personel_delete"),
    path('feedback_reason',views.feedback_reason,name="feedback_reason"),
    path('feedback_source',views.feedback_source,name="feedback_source"),
    path('feedback_reason_delete/<int:id>',views.feedback_reason_delete,name="feedback_reason_delete"),
    path('feedback_source_delete/<int:id>',views.feedback_source_delete,name="feedback_source_delete"),
    path('feedback_reason_update/<int:id>',views.feedback_reason_update,name="feedback_reason_update"),
    path('feedback_source_update/<int:id>',views.feedback_source_update,name="feedback_source_update"),
    path('admin_register',views.admin_register,name="admin_register"),
    path('admin_register_update/<int:id>',views.admin_register_update,name="admin_register_update"),
    path('admin_register_delete/<int:id>',views.admin_register_delete,name="admin_register_delete"),
    path('admin_register_personel',views.admin_register_personel,name="admin_register_personel"),
    path('admin_register_personel_update/<int:id>',views.admin_register_personel_update,name="admin_register_personel_update"),
    path('admin_register_personel_delete/<int:id>',views.admin_register_personel_delete,name="admin_register_personel_delete"),


    path('d_admin_index',views.d_admin_index,name="d_admin_index"),
    path('d_admin_feedback_detail/<int:id>',views.d_admin_feedback_detail,name="d_admin_feedback_detail"),
    path('d_admin_cozuldu',views.d_admin_cozuldu,name="d_admin_cozuldu"),
    path('files_read/<int:id>',views.files_read,name="files_read"),
    path('d_admin_update',views.d_admin_update,name="d_admin_update"),

]

"""
  path('feedback_status_create/<int:id>',views.feedback_status_create,name="feedback_status_create"),
  path('feedback_detail/<int:id>',views.feedback_detail,name="feedback_detail"),
  path('feedbackdepartment_update/<int:id>',views.feedbackdepartment_update,name="feedbackdepartment_update"),

   path('feedback_status_update/<int:id>',views.feedback_status_update,name="feedback_status_update"), ---> department_admin/feedback_status sil

  path('admin_index',views.admin_index,name="admin_index"),

  path('feedback_admin_update/<int:id>',views.feedback_admin_update,name="feedback_admin_update"), ---->admin/feedback_admin_update , feedback_admin_update.html

  admin_department.html sill!!!
"""

project/urls.py
from django.contrib import admin
from django.urls import path,include
from feedback import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name="index"),
    path('feedbacks/',include("feedback.urls")),
    path('user/',include("user.urls"),)
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
    path('all_department',views.all_department,name="all_department"),
    path('department_detail/<int:id>',views.department_detail,name="department_detail"),
"""

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login/",views.login,name="login"),
    path("logout/",views.logout,name="logout"),
]

"""
    path("d_login",views.d_login,name="d_login"),
    path("a_login",views.a_login,name="a_login"),
"""

feedback/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User

country_choices=(
    ("Türkiye","Türkiye"),
    ("Almanya","Almanya"),
    ("Amerika Birleşik Devletleri","Amerika Birleşik Devletleri"),
    ("Arjantin","Arjantin"),
    ("Azerbaycan","Azerbaycan"),
    ("Brezilya","Brezilya"),
    ("Bulgaristan","Bulgaristan"),
    ("Danimarka","Danimarka"),
    ("Fransa","Fransa"),
    ("Gürcistan","Gürcistan"),
    ("Hollanda","Hollanda"),
    ("Irak","Irak"),
    ("İngiltere","İngiltere"),
    ("İran","İran"),
    ("İspanya","İspanya"),
    ("İtalya","İtalya"),
    ("Uruguay","Uruguay"),
)

city_choices=(
    ("İstanbul(Anadolu)","İstanbul(Anadolu)"),
    ("İstanbul(Avrupa)","İstanbul(Avrupa)"),
    ("Ankara","Ankara"),
    ("Bursa","Bursa"),
    ("İzmir","İzmir"),
    ("Adana","Adana"),
    ("Adıyaman","Adıyaman"),
    ("Afyonkarahisar","Afyonkarahisar"),
    ("Ağrı","Ağrı"),
    ("Aksaray","Aksaray"),
)

status_choices=(
    ("Aktif","Aktif"),
    ("Pasif","Pasif"),
)

dprt_choice= (
    ("Acil Servis", "Acil Servis"),
    ("Algoloji", "Algoloji"),
    ("Aile Hekimliği" , "Aile Hekimliği"),
    ("Amatem","Amatem(Alkol ve Madde Bağımlığı)"),
    ("Anesteziyoloji ve Reanimasyon","Anesteziyoloji ve Reanimasyon"),
    ("Beyin ve Sinir Cerrahisi","Beyin ve Sinir Cerrahisi"),
    ("Cerrahi Onkolojisi","Cerrahi Onkolojisi"),
    ("Çocuk Bölümü","Çocuk Bölümü"),
    ("Çocuk Diş Hekimliği","Çocuk Diş Hekimliği"),
    ("Cildiye","Deri ve Zührevi Hastalıkları"),
    ("Diş Hekimliği","Diş Hekimliği"),
    ("Endodonti","Endodonti"),
    ("Endokrin","Endokrinoloji ve Metabolizma Hastalıkları"),
    ("Enfeksiyon","Enfeksiyon Hastalıkları ve Klinik Mikrobiyoloji"),
    ("Fiziksel Tıp ve Rehabilitasyon","Fiziksel Tıp ve Rehabilitasyon"),
    ("Gastroenteroloji","Gastroenteroloji"),
    ("Gelişimsel Pediatri","Gelişimsel Pediatri"),
    ("Genel Cerrahi","Genel Cerrahi"),
    ("Geriatri","Geriatri"),
    ("Göğüs Cerrahisi","Göğüs Cerrahisi"),
    ("Göz Hastalıkları","Göz Hastalıkları"),
    ("Hematoloji","Hematoloji"),
    ("İç Hastalıkları(Dahiliye)", "İç Hastalıkları(Dahiliye)"),
    ("İmmünoloji ve Alerji Hastalıkları","İmmünoloji ve Alerji Hastalıkları"),
    ("İş ve Mesleki Hastalıkları","İş ve Mesleki Hastalıkları"),
    ("Kadın Hastalıkları ve Doğum","Kadın Hastalıkları ve Doğum"),
    ("Kalp ve Damar Cerrahisi","Kalp ve Damar Cerrahisi"),
    ("Kulak Burun Boğaz Hastalıkları","Kulak Burun Boğaz Hastalıkları"),
    ("Nefroloji","Nefroloji"),
    ("Nöroloji","Nöroloji"),
    ("Ordodonti","Ordodonti"),
    ("Perinatoloji","Perinatoloji"),
    ("Plastik Rekonstrüktif Estetik Cerrahi","Plastik Rekonstrüktif Estetik Cerrahi"),
    ("Ruh Sağlığı ve Hastalıkları(Psikiyatri)","Ruh Sağlığı ve Hastalıkları(Psikiyatri)"),
    ("Üroloji","Üroloji"),
    ("Radyoloji","Radyoloji"),
    ("*****","*****"),
) 

type_choice =(
    ("Öneri","Öneri"),
    ("Şikayet","Şikayet"),
    ("Teşekkür","Teşekkür"),
)

reason_choice=(
    ("Kötü Davranış","Kötü Davranış"),
    ("Hijyen Azlığı","Hijyen Azlığı"),
    ("Personelin Tutum ve Davranışı","Personelin Tutum ve Davranışı"),
    ("Personel Azlığı","Personel Azlığı"),
    ("Refakatçi İmkanı","Refaketçi İmkanı"),
    ("Hastane Olanakları","Hastane Olanakları"),
    ("Diğer","Diğer"),
)

source_choice=(
    ("Personel","Personel"),
    ("Hijyen","Hijyen"),
    ("Fiyat","Fiyat"),
)

personel_choice=(
    ("Doktor" , "Doktor"),
    ("Hemşire", "Hemşire"),
    ("Eczacı", "Eczacı"),
    ("Diş Hekimi", "Diş Hekimi"),
    ("Fizyoterapist","Fizyoterapist"),
    ("Ebe","Ebe"),
    ("Anestezi Teknikeri","Anestezi Teknikeri"),
    ("Laboratuvar Teknikeri","Laboratuvar Teknikeri"),
    ("Odyometri Teknikeri","Odyometri Teknikeri"),
    ("Ameliyathane Teknikeri","Ameliyathane Teknikeri"),
    ("Radyoloji Teknikeri","Radyoloji Teknikeri"),
    ("Sekreter","Sekreter"),
    ("Temizlik Personeli","Temizlik Personeli"),
    ("Güvenlik", "Güvenlik"),
    ("Hasta Bakıcı","Hasta Bakıcı"),
    ("Diğer","Diğer"),
)

priority_choice=(
    ("Normal","Normal"),
    ("Orta","Orta"),
    ("Yüksek","Yüksek"),
)

f_status_choice = (
    ("Açık","Açık"),
    ("İşlemde","İşlemde"),
    ("Çözüldü","Çözüldü"),
)

class Country(models.Model):
    name = models.CharField(max_length=27,verbose_name="name",default="Türkiye")
    def __str__(self):
        return self.name

class City(models.Model):
    IdCountry = models.ForeignKey(Country, on_delete=models.CASCADE, verbose_name="country")
    name = models.CharField(max_length=27,verbose_name="city")
    def __str__(self):
        return self.name


class Company(models.Model):
    name = models.CharField(max_length=100,verbose_name="company_name")
    status = models.CharField(max_length=5,verbose_name="company_status",default="Pasif",choices=status_choices)
    idcountry = models.ForeignKey(Country,on_delete=models.CASCADE,verbose_name="idcountry")
    idcity = models.ForeignKey(City,on_delete=models.CASCADE,verbose_name="idcity")
    address = models.TextField(max_length=150,verbose_name="adress")
    def __str__(self):
        return self.name

class Department(models.Model):
    idcompany= models.ForeignKey(Company,on_delete=models.CASCADE,verbose_name="dprt_company")
    name = models.CharField(max_length=50,verbose_name="Departman Adı")
    status = models.CharField(max_length=6,verbose_name="Durum",choices=status_choices)
    def __str__(self):
        return self.name

class FeedbackType(models.Model):
    idcompany= models.ForeignKey(Company,on_delete=models.CASCADE,verbose_name="f_type_company")
    name = models.CharField(max_length=8,verbose_name="Talep-Şikayet Tipi")
    status = models.CharField(max_length=6,verbose_name="Durum",choices=status_choices)
    def __str__(self):
        return self.name

class FeedbackReason(models.Model):
    idcompany= models.ForeignKey(Company,on_delete=models.CASCADE,verbose_name="f_reason_company")
    name = models.CharField(max_length=35,verbose_name="Talep-Şikayet Nedeni Adı")
    status = models.CharField(max_length=6,verbose_name="Durum",choices=status_choices)
    def __str__(self):
        return self.name

class FeedbackSource(models.Model):
    idcompany= models.ForeignKey(Company,on_delete=models.CASCADE,verbose_name="f_source_company")
    name = models.CharField(max_length=35,verbose_name="Talep-Şikayet Genel Neden Adı")
    status = models.CharField(max_length=6,verbose_name="Durum",choices=status_choices)
    def __str__(self):
        return self.name

class FeedbackPersonel(models.Model):
    idcompany= models.ForeignKey(Company,on_delete=models.CASCADE,verbose_name="Hastane")
    name = models.CharField(max_length=35,verbose_name="Personel Adı")
    def __str__(self):
        return self.name

class FeedbackPriorityLevel(models.Model):
    idcompany= models.ForeignKey(Company,on_delete=models.CASCADE,verbose_name="f_priority_company")
    name = models.CharField(max_length=35,verbose_name="f_priority_name",choices=priority_choice)
    def __str__(self):
        return self.name


class FeedbackStatus(models.Model):
    IdCompany = models.ForeignKey(Company,verbose_name="status_ıdcompany",on_delete=models.CASCADE)
    name = models.CharField(max_length=7,verbose_name="Durum Adı",choices=f_status_choice)

    def __str__(self):
        return self.name


class Feedback(models.Model):
    IdCompany = models.ForeignKey(Company,on_delete=models.CASCADE,verbose_name="Hastane")
    Name = models.CharField(max_length=30,verbose_name="Ad",null=True,blank=True)
    Surname = models.CharField(max_length=30,verbose_name="Soyad",null=True,blank=True)
    Email = models.EmailField(max_length=40,verbose_name="Email")
    PhoneNumber = PhoneNumberField(default="",verbose_name="Telefon Numarası")
    Content = models.TextField(verbose_name="Talep-Şikayet İçeriği")
    Photo = models.FileField(blank=True,null=True,verbose_name="Resim")
    IdDepartment = models.ForeignKey(Department,on_delete=models.CASCADE,verbose_name="Talep-Şikayet Departmanı")
    IdFeedbackType = models.ForeignKey(FeedbackType,on_delete=models.CASCADE,verbose_name="Talep-Şikayet Tipi")
    IdFeedbackSource = models.ManyToManyField(FeedbackSource,verbose_name="Talep-Şikayet Nedeni (Çoklu Seçim Yapılabilir) ")
    IdFeedbackReason = models.ManyToManyField(FeedbackReason,verbose_name="Talep-Şikayet Nedeni (Detay) (Çoklu Seçim Yapılabilir) ")
    IdFeedbackPersonel =models.ManyToManyField(FeedbackPersonel,verbose_name="Talep-Şikayet Personeli (Çoklu Seçim Yapılabilir) ")
    FeedbackOpenDate = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    IdFeedbackPriorityLevel = models.ForeignKey(FeedbackPriorityLevel,null=True,on_delete=models.CASCADE,verbose_name="Talep-Şikayet Öncelik Seviyesi")
    IdFeedbackStatus = models.ForeignKey(FeedbackStatus,default=1,verbose_name="Talep-Şikayet Durumu",on_delete=models.CASCADE)
    FeedbackClosedDate= models.DateTimeField(auto_now=True,verbose_name="Talep-Şikayet Son İşlem Saati")
    LastSolveDate = models.DateTimeField(null=True,verbose_name="Talep ve Şikayetin Yanıtı İçin Gerekli Zaman(Ör: ..-..-.... 17:40)")
    DurationTime = models.CharField(max_length=100,verbose_name="Geçen Zaman",null=True)
    
    def __str__(self):
        return self.Content

    class Meta:
        ordering = ["IdFeedbackStatus__id","-IdFeedbackPriorityLevel__id"]

    
class FeedbackStatusHistory(models.Model):
    history_feedback = models.ForeignKey(Feedback,verbose_name="history_feedback",on_delete=models.CASCADE)
    history_status = models.ForeignKey(FeedbackStatus,verbose_name="Talep-Şikayet Durumu",on_delete=models.CASCADE)
    history_department = models.ForeignKey(Department,verbose_name="Talep-Şikayet Departmanı",on_delete=models.CASCADE)
    history_user = models.ForeignKey(User,verbose_name="Talep-Şikayet Kontrolü Yapan Kişi",on_delete=models.CASCADE)

templates/department_admin/d_admin_update.html
{% extends "department_admin/layout.html" %}

{% block content %}
{% load crispy_forms_tags %}
<h3 class="text-success">Bilgileri Güncelleme</h3><hr>
<h6 class="text-warning" >* Alanların Doldurulması Zorunludur!</h6>
<h6 class="text-warning" >Bilgileri Değiştirmek İçin Kullanılan Şifrenin Girilmesi Zorunludur!</h6><br><br>
<form method="POST">
    {% csrf_token %}
    <div class="container text-center">
        <div class="row">
            <div class="col">
            {{form2|crispy}}
            </div>
            <div class="col">
			<div class="mb-3">
					<label class="form-label">Ad</label>
					<input type="text" class="form-control" name="first_name" value="{% if user.first_name %}{{user.first_name}}{% else%}--{% endif %}">
				</div>
                <div class="mb-3">
					<label class="form-label">Soyad</label>
					<input type="text" class="form-control" name="last_name" value="{% if user.last_name %}{{user.last_name}}{% else%}--{% endif %}">
				</div>
				<div class="mb-3">
					<label class="form-label">Email</label>
					<input type="email" class="form-control" name="email" value="{{user.email}}">
				</div>
                <div class="mb-3">
					<label class="form-label">Kullanılan Şifre</label>
					<input type="password" class="form-control" name="last_password">
				</div>
                <div class="mb-3">
					<label class="form-label">Yeni Parola</label>
					<input type="password" class="form-control" name="password">
				</div>
                <div class="mb-3">
					<label class="form-label">Yeni Parola(Tekrar)</label>
					<input type="password" class="form-control" name="confirm">
				</div>
            </div>
        </div>
    </div>
    <br>
    <div class="d-flex justify-content-end ">
        <div class="col-example">
        <button type="submit" class="form-control btn btn-danger">Bilgilerimi Güncelle</button>
        </div>
    </div>
    
</form>
{% endblock  %}

templates/department_admin/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hastane Feedback</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <a class="navbar-brand" href="{% url 'feedback:d_admin_index' %}">Departman Admini Paneli</a>
            <ul class="navbar-nav ms-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item ">
                        <a class="nav-link active" href="{% url 'user:logout' %}">Çıkış</a>
                    </li>
                {% endif %}
            </ul>              
            </div>
        </div>
    </div>
    </nav>
    <div style="margin-top: 100px; margin-bottom:100px; margin-left:25px;" >
        <div class="row">
            <div class="col-3">
                <div class="list-group"> <!--<img src="/media/house-door.svg" width="18" height="18" >  -->
                    <a href="{% url 'feedback:d_admin_index' %}" class="list-group-item list-group-item-action list-group-item-warning ">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-house-door" viewBox="0 0 16 16" align="middle">
                        <path d="M8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4.5a.5.5 0 0 0 .5-.5v-4h2v4a.5.5 0 0 0 .5.5H14a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146ZM2.5 14V7.707l5.5-5.5 5.5 5.5V14H10v-4a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5v4H2.5Z"/>
                    </svg><b>&emsp;Anasayfa</b></a>

                    <div class="col-example" >
                    <a class="list-group-item list-group-item-action" data-bs-toggle="collapse" href="#collapseExampleTalep" role="button" aria-expanded="false" aria-controls="collapseExample">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-card-list" viewBox="0 0 16 16">
                        <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
                        <path d="M5 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 5 8zm0-2.5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm0 5a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5zm-1-5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zM4 8a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm0 2.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0z"/>
                    </svg><b>&emsp;Talepler-Şikayetler</b></a>
                    </div>
                        <div class="collapse" id="collapseExampleTalep" >
                        <a href="{% url 'feedback:d_admin_index' %}" class="list-group-item list-group-item-action">
                        &emsp;&emsp;<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark-check" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M10.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                        <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
                        </svg>&emsp;<b>İşlemde</b>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                        {% block talep %}
                        {% endblock talep %}</a>
                        <a href="{% url 'feedback:d_admin_cozuldu' %}" class="list-group-item list-group-item-action">
                        &emsp;&emsp;<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bookmark-check" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M10.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                        <path d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z"/>
                        </svg>&emsp;<b>Tamamlanmış</b></a>
                        </div>

                    <a href="{% url 'feedback:d_admin_update' %}" class="list-group-item list-group-item-action list-group-item-warning">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                    </svg><b>&emsp;Kullanıcı Bilgileri</b></a>
                </div>
            </div>
            <div class="col-8" style="margin-left:25px;">
                    {% if messages %}
                        {% for message in messages %}
                            
                            {% if message.tags == "info" %}
                                <div class="alert alert-danger">{{ message }}</div>
                        
                            {% else %}
                                <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                            {% endif %}
                        {% endfor %}

                    {% endif %}
                {% block content %}

                {% endblock content %}<br>
                
                {% block ek %}
                
                {% endblock ek %}
            </div>
        </div>
    </div>

    <div style="margin-top: 100px; margin-bottom:100px;" class="container" >
        
        {% block body %}
    
        {% endblock body %}
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>

</body>
</html>

templates/department_admin/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

    <h3>Departman Girişi</h3>
    <hr>
    <div class="row">
        <div class="col-md-3 offset-md-3">

            <form method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger">Giriş</button>
            </form>
        </div>
    </div>
{% endblock  %}