feedback/urls.py
from django.urls import path
from . import views

app_name="feedback"

urlpatterns = [
    path('feedback/',views.feedback,name="feedback"),

   
    path('admin_all_department',views.admin_all_department,name="admin_all_department"),
    path('department_delete/<int:id>',views.department_delete,name="department_delete"),
    path('department_update/<int:id>',views.department_update,name="department_update"),
    path('admin_all_feedback',views.admin_all_feedback,name="admin_all_feedback"),
    path('admin_feedback',views.admin_feedback,name="admin_feedback"),
    path('admin_feedback_detail/<int:id>',views.admin_feedback_detail,name="admin_feedback_detail"),
    path('admin_feedback_islemde',views.admin_feedback_islemde,name="admin_feedback_islemde"),
    path('admin_feedback_cozuldu',views.admin_feedback_cozuldu,name="admin_feedback_cozuldu"),
    path('aktif_pasif_update/<int:id>',views.aktif_pasif_update,name="aktif_pasif_update"),
    path('feedback_type',views.feedback_type,name="feedback_type"),
    path('feedback_type_update/<int:id>',views.feedback_type_update,name="feedback_type_update"),
    path('feedback_type_delete/<int:id>',views.feedback_type_delete,name="feedback_type_delete"),
    path('admin_personel',views.admin_personel,name="admin_personel"),
    path('admin_personel_update/<int:id>',views.admin_personel_update,name="admin_personel_update"),
    path('admin_personel_delete/<int:id>',views.admin_personel_delete,name="admin_personel_delete"),
    path('feedback_reason',views.feedback_reason,name="feedback_reason"),
    path('feedback_source',views.feedback_source,name="feedback_source"),
    path('feedback_reason_delete/<int:id>',views.feedback_reason_delete,name="feedback_reason_delete"),
    path('feedback_source_delete/<int:id>',views.feedback_source_delete,name="feedback_source_delete"),
    path('feedback_reason_update/<int:id>',views.feedback_reason_update,name="feedback_reason_update"),
    path('feedback_source_update/<int:id>',views.feedback_source_update,name="feedback_source_update"),
    path('admin_register',views.admin_register,name="admin_register"),
    path('admin_register_update/<int:id>',views.admin_register_update,name="admin_register_update"),
    path('admin_register_delete/<int:id>',views.admin_register_delete,name="admin_register_delete"),
    path('admin_register_personel',views.admin_register_personel,name="admin_register_personel"),
    path('admin_register_personel_update/<int:id>',views.admin_register_personel_update,name="admin_register_personel_update"),
    path('admin_register_personel_delete/<int:id>',views.admin_register_personel_delete,name="admin_register_personel_delete"),


    path('d_admin_index',views.d_admin_index,name="d_admin_index"),
    path('d_admin_feedback_detail/<int:id>',views.d_admin_feedback_detail,name="d_admin_feedback_detail"),
    path('d_admin_cozuldu',views.d_admin_cozuldu,name="d_admin_cozuldu"),
    path('files_read/<int:id>',views.files_read,name="files_read"),
    path('d_admin_update',views.d_admin_update,name="d_admin_update"),

]

"""
  path('feedback_status_create/<int:id>',views.feedback_status_create,name="feedback_status_create"),
  path('feedback_detail/<int:id>',views.feedback_detail,name="feedback_detail"),
  path('feedbackdepartment_update/<int:id>',views.feedbackdepartment_update,name="feedbackdepartment_update"),

   path('feedback_status_update/<int:id>',views.feedback_status_update,name="feedback_status_update"), ---> department_admin/feedback_status sil

  path('admin_index',views.admin_index,name="admin_index"),

  path('feedback_admin_update/<int:id>',views.feedback_admin_update,name="feedback_admin_update"), ---->admin/feedback_admin_update , feedback_admin_update.html

  admin_department.html sill!!!
"""

project/urls.py
from django.contrib import admin
from django.urls import path,include
from feedback import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name="index"),
    path('feedbacks/',include("feedback.urls")),
    path('user/',include("user.urls"),)
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
    path('all_department',views.all_department,name="all_department"),
    path('department_detail/<int:id>',views.department_detail,name="department_detail"),
"""

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("login/",views.login,name="login"),
    path("logout/",views.logout,name="logout"),
]

"""
    path("d_login",views.d_login,name="d_login"),
    path("a_login",views.a_login,name="a_login"),
"""

templates/all_department.html
{% extends "layout.html" %}

{% block body %}
<table class="table table-bordered">

  <thead class="thead-dark">
    <tr>
      <th scope="col">Aktif Departmanlar</th>
      <th scope="col">Pasif Departmanlar</th>
    </tr>
  </thead>

  <tbody>
  {% for department in departments %}
        <tr>
            <td>
            {% if department.status == "Aktif" %}
                <a class="text-success" href="{% url 'department_detail' department.id %}"><b>{{department.name}}</b></a>
            {% endif %}
            </td>
            <td class= "text-warning">
            {% if department.status == "Pasif" %}
                <b>{{department.name}}</b>
            {% endif %}
            </td>
        </tr>
  {% endfor %}
  </tbody>

</table>

{% endblock  %}

templates/department_detail.html
{% extends "layout.html" %}

{% block body %}
<br>
<h4 class="text-danger">{{dprt.name}} Departmanı</h4>
<br><br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">Tip</th>
      <th scope="col">Neden</th>
      <th scope="col">Detay</th>
      <th scope="col">Personel</th>
      <th scope="col">Oluşturulma Tarihi</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
       {% for feedback in feedbacks %}
        <tr>
            <td>{{feedback.IdFeedbackType}}</td>
            <td>
            {% for f_source in feedback.IdFeedbackSource.all %}
                <ul><li>{{f_source.name}}</li></ul>
            {% endfor %}
            </td>
            <td>
            {% for f_reason in feedback.IdFeedbackReason.all %}
                <ul><li>{{f_reason.name}}</li></ul>
            {% endfor %}
            </td>
            <td>
            {% for f_personel in feedback.IdFeedbackPersonel.all %}
                <ul><li>{{f_personel.name}}</li></ul>
            {% endfor %}
            </td>
            <td>{{feedback.FeedbackOpenDate}}</td>
            {% if request.user.username == "admin" %}
                <td><a href="{% url 'feedback:admin_feedback_detail' feedback.id %}" class="text-danger">İncele</a></td>
            {% else %}
                <td><a href="{% url 'feedback:feedback_detail' feedback.id %}" class="text-danger">İncele</a></td>
            {% endif %}

            
        </tr>
 {% endfor %}
  </tbody>
</table>

{% endblock  %}

templates/feedback_create.html
{% extends "layout.html" %}

{% block body %}
    {% load crispy_forms_tags %}
    <h3 class="text-success">Talep-Şikayet Oluştur</h3>
    <hr>
    <h6 class="text-warning" >* Alanların Doldurulması Zorunludur!</h6><br>
    <div class="row">
        <div class = "col-md-6 offset-md-3">

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger">Oluştur</button>
            </form>
        </div>
    </div>

{% endblock  %}

templates/feedback_detail.html
{% extends "layout.html" %}

{% block body %}
<br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col" class="text-success">Ad-Soyad</th>
      <th scope="col" class="text-success">Email</th>
      <th scope="col" class="text-success">Telefon Numarası</th>
      <th scope="col" class="text-success">Talep-Şikayet Oluşturulma Tarihi</th>
    </tr>
  </thead>
  <tbody>
        <tr>
            <td> 
            {% if feedback.Name == None or feedback.Surname == None %}
                <div class="col-6">Girilmemiş</div>
            {% else %}
                <div class="col-6">{{feedback.Name}} {{feedback.Surname}}</div>
            {% endif %}
            </td>
            <td>{{feedback.Email}}</td>
            <td>{{feedback.PhoneNumber}}</td>
            <td>{{feedback.FeedbackOpenDate}}</td>
        </tr>       
  </tbody>
</table><br>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col" class="text-success">Talep-Şikayet Tipi</th>
      <th scope="col" class="text-success">Talep-Şikayet Sahibi Personel</th>
      <th scope="col" class="text-success">Talep-Şikayet Nedeni(Genel)</th>
      <th scope="col" class="text-success">Talep-Şikayet Nedeni</th>
    </tr>
  </thead>
  <tbody>
        <tr>
            <td>{{feedback.IdFeedbackType}}</td>
            <td>
                {% for f_personel in feedback.IdFeedbackPersonel.all %}
                    <ul><li>{{f_personel.name}}</li></ul>
                {% endfor %}
            </td>
            <td> 
                {% for f_source in feedback.IdFeedbackSource.all %}
                    <ul><li>{{f_source.name}}</li></ul>
                {% endfor %}
            </td>
            <td>
                {% for f_reason in feedback.IdFeedbackReason.all %}
                    <ul><li>{{f_reason.name}}</li></ul>
                {% endfor %}
            </td>
        </tr>       
  </tbody>
</table><br>

<h6 class="text-success"><b>İçerik:</b></h6><p>{{feedback.Content}}</p><br>
<h6 class="text-success"><b>Resim:</b></h6>
{% if feedback.Photo == "" %}
    <p>Yüklenmemiş</p>
{% else %}
    <p>{{feedback.Photo}}</p>
{% endif %}
<br><br>

    <table class="table table-bordered">
    <thead>
        <tr>
        <th scope="col" class="text-warning">Talep-Şikayet Öncelik Seviyesi</th>
        <th scope="col" class="text-warning">Talep-Şikayet Son İşlem Saati</th>
        <th scope="col" class="text-warning">Talep ve Şikayetin Yanıtı İçin Gerekli Zaman(Gün)</th>
        <th scope="col" class="text-warning">Geçen Süre</th>
        </tr>
    </thead>
    <tbody>
            <tr>
                <td>{{feedback.IdFeedbackPriorityLevel}}</td>
                <td>{{feedback.FeedbackClosedDate}}</td>
                <td>{{feedback.LastSolveDate}}</td>
                <td>{{feedback.DurationTime}} Gün</td>
            </tr>       
    </tbody>
    </table><br>


{% endblock  %}

templates/feedbackdepartment_update.html
{% extends "layout.html" %}

{% block body %}
    {% load crispy_forms_tags %}
    <h3 class="text-success">Talep-Şikayet Güncelleme</h3>
    <hr>
    <h6 class="text-warning">* Alanların Doldurulması Zorunludur!</h6><br>
    <div class="row">
        <div class = "col-md-6 offset-md-3">
            <form method="POST" >
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger">Güncelle</button>
            </form>
        </div>
    </div>

{% endblock  %}

templates/files_read.html
{% extends "layout.html" %}

{% block body %}
<h5 class="text-info">Dosya İçeriği</h5>
<hr>
<p>{{f}}</p>
{% endblock  %}

templates/index.html
{% extends "layout.html" %}

{% block body %}
<p>Hastane Admini:<br>Kullanıcı Adı:<b>admin</b>&emsp;Şifre:<b>admin.123</b> </p><br><br>
<p>Departman Admini:<br>Kullanıcı Adı:<b>acil_servis_admin</b>&emsp;Şifre:<b>admin_123</b> </p>
{% endblock  %}

templates/layout.html
<!DOCTYPE html>
{% load static %} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hastane Feedback</title>

    <link  rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.2.1.min.js' %}" ></script>
    
</head>
<body>
    
    {% include "includes/navbar.html" %}
   
    <div style="margin-top: 75px; margin-bottom:100px;" class="container-lg" >
        
        {% if messages %}
            {% for message in messages %}
                
                {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
            
                {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                {% endif %}
            {% endfor %}

        {% endif %}
        
        {% block body %}
    
        {% endblock body %}
        
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}" ></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}" ></script>
</body>
</html>

<!--   


 <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
-->

templates/login.html
{% extends "layout.html" %}


{% block body %}
{% load crispy_forms_tags %}
    <h3 class ="text-danger">Giriş Yap</h3>
    <hr>
    <div class="row">
        <div class="col-md-3 offset-md-3">
            <form method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger">Giriş</button>
            </form>
        </div>
    </div>
    
{% endblock %}